# Generated by Django 5.0.6 on 2024-07-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customer_user_alter_staff_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Staff', 'Staff')], default='customer', max_length=50),
        ),
    ]
