# Generated by Django 5.0.6 on 2024-07-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Staff', 'Staff')], default='Customer', max_length=50),
        ),
    ]
